##
# profiles
##
spring:
    profiles:
        active: dev
#spring.profiles: prod
#spring.profiles.include: proddb,prodmq

##
# Mbean
# SpringApplicationAdminMXBean not work 
##
#spring.application.admin.enabled=false
#local.server.port=9090

##
# static resource locatino
##
#spring.resources.static-locations=classpath:/htmls
#spring.resources.add-mappings=false

##
# security properties
##
security:
    basic:
        enabled: false

###############################
#  Custom properties
###############################
app:
    async:
        corePoolSize: 2
        maxPoolSize: 50
        queueCapacity: 10000
    liquibase:
        changeLog: classpath:db/liquibase/master.xml