##
# profiles
##
spring:
    profiles:
        active: dev
    thymeleaf:
        mode: HTML5
    messages:
        basename: classpath:/i18n/messages 
#spring.profiles: prod
#spring.profiles.include: proddb,prodmq

##
# Mbean
# SpringApplicationAdminMXBean not work 
##
#spring.application.admin.enabled=false
#local.server.port=9090

##
# static resource locatino
##
#spring.resources.static-locations=classpath:/htmls
#spring.resources.add-mappings=false

##
# security properties
##
security:
    basic:
        enabled: false

##
# flyway 
##       
flyway:
  baseline-on-migrate: true
  table: flyway_schema_version
  encoding: UTF-8
##
# multipart properties
##
multipart:
  max-file-size: 2097152

###############################
#  Custom properties
###############################
app:
    async:
        corePoolSize: 2
        maxPoolSize: 50
        queueCapacity: 10000
    liquibase:
        changeLog: classpath:db/liquibase/master.xml